### PR TITLE
Install GDAL data files

### PR DESCRIPTION
**Pull request by johnkit**
Need to include GDAL data files in applications that embed gdal

### CODE REVIEW

**Comment by mathstuf** [comment]
If this makes the correct directory structure, looks fine to me (looks like `/usr/share/gdal/foo.csv` to me, but maybe the `data` directory is preserved).

**Comment by johnkit** [comment]
Like always, there's no consistent standard
- On unix, the documented default is /usr/local/share/gdal; although on my machine it's actually at /usr/share/gdal/<version>
- On Windows, the default is C:\GDAL\data

Whatever the case, DataBrowser needs to set an env variable (GDAL_DATA) at runtime to this directory, so my thinking is to make the data directory a known relative-path from the executable.

**Comment by johnkit** [comment]
Oops, I hit the "Comment" button too soon. Should we set this for the default paths, as listed in the GDAL faq, and have a way to override it for DataBrowserSuperBuild?

**Comment by mathstuf** [comment]
A known-relative path sounds good for the superbuild.

**Comment by johnkit** [comment]
OK, I finally got back to this. I updated the install path to what the GDAL wiki describes as the default folders, which are different for windows and unix, of course....

**Pull request merged**
